apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deployment.fullname" . }}-v2
  labels: {{- include "deployment.labels" . | nindent 4 }}
  {{- with .Values.commonLabels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.versionTwo.autoscaling.enabled }}
  replicas: {{ .Values.versionTwo.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      labels: {{- include "deployment.labels" . | nindent 8 }}
        version: v2
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext: {{- . | toYaml | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      serviceAccountName: {{ include "deployment.fullname" . }}
      containers:
        - name: {{ include "deployment.fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.versionTwo.command }}
          command: {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.containerPorts }}
          ports: {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.versionTwo.args }}
          args: {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.versionTwo.env }}
          env: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.versionTwo.secrets }}
          envFrom: {{- include "deployment.envFrom" . | trim | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
          {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:   
          {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources: {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext: {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.volumeMounts .Values.versionTwo.configmap.create }}
          volumeMounts:
          {{- if .Values.versionTwo.configmap.create }}
            - name: configmap-volume
              mountPath: {{ .Values.versionTwo.configmap.mountPath }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
      {{- if or .Values.volumeMounts .Values.versionTwo.configmap.create }}
      volumes:
        {{- if .Values.versionTwo.configmap.create }}
        - name: configmap-volume
          configMap:
            name: {{ include "deployment.fullname" . }}-v2
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
