# Default values for ksvc.

fullnameOverride: ""

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

podAnnotations: {}

serviceAccount:
  create: false
  annotations: {}
  imagePullSecrets: []

securityContext: {}

livenessProbe: {}

readinessProbe:
  httpGet:
    path: /
    port: http
  successThreshold: 1

containerSecurityContext: {}

containerPorts: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

labels: {}

env: []

secrets: []

files: {}

secretMounts: {}

command: []

args: []

ingress: public

autoscaling:
  minReplicas: 0
  maxReplicas: 10

serviceMonitor:
  create: false
  endpoints: []
