apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deployment.fullnameOverride" . }}
  labels: {{- include "deployment.labels" . | nindent 4 }}
  {{- with .Values.commonLabels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      labels: {{- include "deployment.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext: {{- . | toYaml | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      serviceAccountName: {{ include "deployment.fullnameOverride" . }}
      containers:
        - name: {{ include "deployment.fullnameOverride" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command: {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.containerPorts }}
          ports: {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args: {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.env }}
          env: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.secrets }}
          envFrom: {{- include "envFrom" . | trim | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
          {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:   
          {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources: {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext: {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts: {{- include "volumeMounts" . | trim | nindent 12 }}
      volumes: {{- include "volumes" . | trim | nindent 8 }}
